// Investment configuration (Model)
const investments = [
  {
    name: "Lemonade Stand",
    description: "Start small. Squeeze every cent.",
    image: "img/lemonade.jpg",
    initialCost: 50,
    upgradeCost: 58,
    payout: 5,
    interval: 15,
    unlockAt: 50,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Garage Sale Empire",
    description: "Sell grandma's junk for profit.",
    image: "img/garage.png",
    initialCost: 75,
    upgradeCost: 86,
    payout: 7,
    interval: 14,
    unlockAt: 75,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Mom’s Basement Startup",
    description: "Funded by ramen and ambition.",
    image: "img/startup.png",
    initialCost: 110,
    upgradeCost: 126,
    payout: 10,
    interval: 13,
    unlockAt: 110,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Local Pizza Chain",
    description: "Grease the wheels of commerce.",
    image: "img/pizza.png",
    initialCost: 160,
    upgradeCost: 184,
    payout: 14,
    interval: 13,
    unlockAt: 160,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Neighborhood Crypto Miner",
    description: "Melt GPUs for passive income.",
    image: "img/crypto.png",
    initialCost: 240,
    upgradeCost: 276,
    payout: 20,
    interval: 12,
    unlockAt: 240,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Influencer Brand Deal Agency",
    description: "Turn clout into cash.",
    image: "img/influencer.png",
    initialCost: 360,
    upgradeCost: 414,
    payout: 30,
    interval: 12,
    unlockAt: 360,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Regional Fast Food Empire",
    description: "Have it your way — everywhere.",
    image: "img/fastfood.png",
    initialCost: 540,
    upgradeCost: 621,
    payout: 45,
    interval: 11,
    unlockAt: 540,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "National Tech Conglomerate",
    description: "Owns three apps and your data.",
    image: "img/tech.png",
    initialCost: 800,
    upgradeCost: 920,
    payout: 60,
    interval: 11,
    unlockAt: 800,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Offshore Investment Scheme",
    description: "Totally legit. Promise.",
    image: "img/offshore.png",
    initialCost: 1200,
    upgradeCost: 1380,
    payout: 80,
    interval: 10,
    unlockAt: 1200,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Artificial Intelligence Mega-Lab",
    description: "Automate the world (and profits).",
    image: "img/ai.png",
    initialCost: 1800,
    upgradeCost: 2070,
    payout: 110,
    interval: 10,
    unlockAt: 1800,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "World Bank Acquisition",
    description: "Set the rates. Rule the game.",
    image: "img/bank.png",
    initialCost: 2700,
    upgradeCost: 3105,
    payout: 160,
    interval: 9,
    unlockAt: 2700,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Interplanetary Mining Corp",
    description: "Mars has more than just dust.",
    image: "img/marsmine.png",
    initialCost: 4100,
    upgradeCost: 4720,
    payout: 230,
    interval: 9,
    unlockAt: 4100,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Time-Travel Real Estate Trust",
    description: "Buy in 1890. Sell in 2200.",
    image: "img/timetravel.png",
    initialCost: 6200,
    upgradeCost: 7130,
    payout: 320,
    interval: 8,
    unlockAt: 6200,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Galactic Stock Exchange",
    description: "Trade across the stars.",
    image: "img/galaxy.png",
    initialCost: 9300,
    upgradeCost: 10700,
    payout: 440,
    interval: 8,
    unlockAt: 9300,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "Multiverse Monopoly Machine",
    description: "Infinite selves. Infinite revenue.",
    image: "img/multiverse.png",
    initialCost: 14000,
    upgradeCost: 16100,
    payout: 600,
    interval: 7,
    unlockAt: 14000,
    level: 0,
    timer: 0,
    active: false
  },
  {
    name: "God Mode Capital",
    description: "Owns everything. Clicks itself.",
    image: "img/godmode.png",
    initialCost: 21000,
    upgradeCost: 24200,
    payout: 800,
    interval: 7,
    unlockAt: 21000,
    level: 0,
    timer: 0,
    active: false
  }
];
