const investments = [
  {
    "name": "Lemonade Stand",
    "description": "Start small. Squeeze every cent.",
    "image": "img/lemonade.png",
    "initialCost": 5,
    "payout": 1.0,
    "interval": 3.0,
    "unlockAt": 5,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Garage Sale Empire",
    "description": "Sell grandma's junk for profit.",
    "image": "img/garagesaleempire.png",
    "initialCost": 8,
    "payout": 1.6,
    "interval": 2.9,
    "unlockAt": 8,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Mom\u2019s Basement Startup",
    "description": "Funded by ramen and ambition.",
    "image": "img/momsbasementstartup.png",
    "initialCost": 13,
    "payout": 2.6,
    "interval": 2.8,
    "unlockAt": 13,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Local Pizza Chain",
    "description": "Grease the wheels of commerce.",
    "image": "img/localpizzachain.png",
    "initialCost": 20,
    "payout": 4.0,
    "interval": 2.7,
    "unlockAt": 20,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Neighborhood Crypto Miner",
    "description": "Melt GPUs for passive income.",
    "image": "img/neighborhoodcryptominer.png",
    "initialCost": 33,
    "payout": 6.6,
    "interval": 2.6,
    "unlockAt": 33,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Influencer Brand Deal Agency",
    "description": "Turn clout into cash.",
    "image": "img/influencerbranddealagency.png",
    "initialCost": 52,
    "payout": 10.4,
    "interval": 2.5,
    "unlockAt": 52,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Regional Fast Food Empire",
    "description": "Have it your way \u2014 everywhere.",
    "image": "img/regionalfastfoodempire.png",
    "initialCost": 84,
    "payout": 16.8,
    "interval": 2.4,
    "unlockAt": 84,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "National Tech Conglomerate",
    "description": "Owns three apps and your data.",
    "image": "img/nationaltechconglomerate.png",
    "initialCost": 134,
    "payout": 26.8,
    "interval": 2.3,
    "unlockAt": 134,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Offshore Investment Scheme",
    "description": "Totally legit. Promise.",
    "image": "img/offshoreinvestmentscheme.png",
    "initialCost": 215,
    "payout": 43.0,
    "interval": 2.2,
    "unlockAt": 215,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Artificial Intelligence Mega-Lab",
    "description": "Automate the world (and profits).",
    "image": "img/artificialintelligencemega-lab.png",
    "initialCost": 344,
    "payout": 68.8,
    "interval": 2.1,
    "unlockAt": 344,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "World Bank Acquisition",
    "description": "Set the rates. Rule the game.",
    "image": "img/worldbankacquisition.png",
    "initialCost": 550,
    "payout": 110.0,
    "interval": 2.0,
    "unlockAt": 550,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Interplanetary Mining Corp",
    "description": "Mars has more than just dust.",
    "image": "img/interplanetaryminingcorp.png",
    "initialCost": 880,
    "payout": 176.0,
    "interval": 1.9,
    "unlockAt": 880,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Time-Travel Real Estate Trust",
    "description": "Buy in 1890. Sell in 2200.",
    "image": "img/time-travelrealestatetrust.png",
    "initialCost": 1407,
    "payout": 281.4,
    "interval": 1.8,
    "unlockAt": 1407,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Galactic Stock Exchange",
    "description": "Trade across the stars.",
    "image": "img/galacticstockexchange.png",
    "initialCost": 2252,
    "payout": 450.4,
    "interval": 1.7,
    "unlockAt": 2252,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Multiverse Monopoly Machine",
    "description": "Infinite selves. Infinite revenue.",
    "image": "img/multiversemonopolymachine.png",
    "initialCost": 3603,
    "payout": 720.6,
    "interval": 1.6,
    "unlockAt": 3603,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "God Mode Capital",
    "description": "Owns everything. Clicks itself.",
    "image": "img/godmodecapital.png",
    "initialCost": 5765,
    "payout": 1153.0,
    "interval": 1.5,
    "unlockAt": 5765,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  }
];