const investments = [
  {
    "name": "Lemonade Stand",
    "description": "Start small. Squeeze every cent.",
    "image": "img/lemonadestand.png",
    "baseCost": 5,
    "payout": 1.25,
    "interval": 3.0,
    "automationCost": 25,
    "unlockAt": 5,
    "requiresPrevious": false,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Garage Sale Empire",
    "description": "Sell grandma's junk for profit.",
    "image": "img/garagesaleempire.png",
    "baseCost": 9,
    "payout": 2.25,
    "interval": 3.5,
    "automationCost": 45,
    "unlockAt": 9,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Mom\u2019s Basement Startup",
    "description": "Funded by ramen and ambition.",
    "image": "img/momsbasementstartup.png",
    "baseCost": 15,
    "payout": 3.75,
    "interval": 5.0,
    "automationCost": 75,
    "unlockAt": 15,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Local Pizza Chain",
    "description": "Grease the wheels of commerce.",
    "image": "img/localpizzachain.png",
    "baseCost": 27,
    "payout": 6.75,
    "interval": 7.5,
    "automationCost": 135,
    "unlockAt": 27,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Neighborhood Crypto Miner",
    "description": "Melt GPUs for passive income.",
    "image": "img/neighborhoodcryptominer.png",
    "baseCost": 47,
    "payout": 11.75,
    "interval": 11.0,
    "automationCost": 235,
    "unlockAt": 47,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Influencer Brand Deal Agency",
    "description": "Turn clout into cash.",
    "image": "img/influencerbranddealagency.png",
    "baseCost": 82,
    "payout": 20.5,
    "interval": 15.5,
    "automationCost": 410,
    "unlockAt": 82,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Regional Fast Food Empire",
    "description": "Have it your way \u2014 everywhere.",
    "image": "img/regionalfastfoodempire.png",
    "baseCost": 144,
    "payout": 36.0,
    "interval": 21.0,
    "automationCost": 720,
    "unlockAt": 144,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "National Tech Conglomerate",
    "description": "Owns three apps and your data.",
    "image": "img/nationaltechconglomerate.png",
    "baseCost": 251,
    "payout": 62.75,
    "interval": 27.5,
    "automationCost": 1255,
    "unlockAt": 251,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Offshore Investment Scheme",
    "description": "Totally legit. Promise.",
    "image": "img/offshoreinvestmentscheme.png",
    "baseCost": 440,
    "payout": 110.0,
    "interval": 35.0,
    "automationCost": 2200,
    "unlockAt": 440,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Artificial Intelligence Mega-Lab",
    "description": "Automate the world (and profits).",
    "image": "img/artificialintelligencemega-lab.png",
    "baseCost": 770,
    "payout": 192.5,
    "interval": 43.5,
    "automationCost": 3850,
    "unlockAt": 770,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "World Bank Acquisition",
    "description": "Set the rates. Rule the game.",
    "image": "img/worldbankacquisition.png",
    "baseCost": 1347,
    "payout": 336.75,
    "interval": 53.0,
    "automationCost": 6735,
    "unlockAt": 1347,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Interplanetary Mining Corp",
    "description": "Mars has more than just dust.",
    "image": "img/interplanetaryminingcorp.png",
    "baseCost": 2357,
    "payout": 589.25,
    "interval": 63.5,
    "automationCost": 11785,
    "unlockAt": 2357,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Time-Travel Real Estate Trust",
    "description": "Buy in 1890. Sell in 2200.",
    "image": "img/time-travelrealestatetrust.png",
    "baseCost": 4125,
    "payout": 1031.25,
    "interval": 75.0,
    "automationCost": 20625,
    "unlockAt": 4125,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Galactic Stock Exchange",
    "description": "Trade across the stars.",
    "image": "img/galacticstockexchange.png",
    "baseCost": 7219,
    "payout": 1804.75,
    "interval": 87.5,
    "automationCost": 36095,
    "unlockAt": 7219,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "Multiverse Monopoly Machine",
    "description": "Infinite selves. Infinite revenue.",
    "image": "img/multiversemonopolymachine.png",
    "baseCost": 12633,
    "payout": 3158.25,
    "interval": 101.0,
    "automationCost": 63165,
    "unlockAt": 12633,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  },
  {
    "name": "God Mode Capital",
    "description": "Owns everything. Clicks itself.",
    "image": "img/godmodecapital.png",
    "baseCost": 22108,
    "payout": 5527.0,
    "interval": 115.5,
    "automationCost": 110540,
    "unlockAt": 22108,
    "requiresPrevious": true,
    "shares": 0,
    "isAutomated": false,
    "timer": 0,
    "active": false
  }
];